# ndarray内存结构

这个结构引用两个对象：一块用于保存数据的存储区域和一个用于描述元素类型的dtype对象

![](http://img.voidcn.com/vcimg/000/000/101/629_2d3_1e9.png)


In [2]:
import numpy as np
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
], dtype=np.float32)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]], dtype=float32)

**`strides`中保存的是当每个轴的下标增加1时，数据存储区中的指针所增加的字节数。**

例如图中的strides为12,4，即：

- 第0轴的下标增加1时，数据的地址增加12个字节：即a[1,0]的地址比a[0,0]的地址要高12个字节，正好是3个单精度浮点数的总字节数；
- 第1轴下标增加1时，数据的地址增加4个字节，如a[1, 1]比a[1, 0]高4个字节，正好是单精度浮点数的字节数。


# 多维数组

多维数组的概念：

- axes(轴)：数组的维度统称为轴
- rank：轴的数量称为rank

一维数组就是一个rank为1的数组，因为它只有一个轴(一维)。下图显示的是一个rank为2(二维)的数组。

![](http://s5.51cto.com/wyfs02/M02/90/6F/wKioL1jweq2TC6FEAABfAUB-BW8153.jpg)

- 第一个轴(维)的长度是2，红线框表示
- 第二个轴(维)的长度是3，蓝线框表示

`ndarray`的主要属性：

- ndim：数组的轴数(维度)
- shape：python的元组类型，其中每个数字分别表示的是各个轴(维)上数组的长度
- size：多维数组里全部元素的总数(等于shape元组里所有数值的乘积)
- dtype：多维数组里元素的类型

其他属性如：

- itemsize：每一个元素所占字节数。如，类型为float64的数组itemsiz属性值为`8(=64/8)`
- nbytes： 这个array的总字节数（`=itemsize*size`）
- real: 所有元素的实数部分
- imag: 所有元素的虚数部分
- flat：平铺成一维的，可索引的一系列的元素组合。可`for x in array.flat`来取得到所有的元素。
- T： 矩阵转置，同`transpose()`方法

In [17]:
print ({
    'ndim': a.ndim,
    'shape': a.shape,
    'size': a.size,
    'dtype': a.dtype
})

{'ndim': 2, 'shape': (3, 3), 'size': 9, 'dtype': dtype('float32')}


# 轴的概念

n 维空间里有 n 个坐标轴（coordinate axis），并且坐标轴互相垂直，每一个点相对于一条坐标轴都有唯一的一个坐标值

在numpy中的多维数组，轴即是元素坐标的索引。比如，第0轴即是第1个索引，延0轴计算就是去掉坐标中的第一个索引。如果一个多维数组的 shape 是 (a1, a2, a3, a4), 那么延轴0计算最后的数组shape 是 (a2, a3, a4), 延轴1计算最后的数组shape是 (a1, a3, a4)

In [30]:
# 三维数组
np.random.seed(123)
b = np.random.randint(0, 5, [3, 2, 2])
b.shape, b.ndim

((3, 2, 2), 3)

In [31]:
b

array([[[2, 4],
        [2, 1]],

       [[3, 2],
        [3, 1]],

       [[1, 0],
        [1, 1]]])

如果将三维数组的每一个二维看做一个平面（`plane，X[0, :, :], X[1, :, :], X[2, :, :]`），三维数组即是这些二维平面层叠（stacked）出来的结果。则:

- axis=0: 表示全部平面上的对应位置
- axis=1: 表示每一个平面的每一列
- axis=2: 表示每一个平面的每一行

抽象的说，axis就是把n维矩阵串成n+1维矩阵的那条线。如图，箭头就是一个轴。
axis参数表明了沿着箭头方向进行操作。当有3个维度时，

- 第1个（axis=0）axis就表达了下标为1的变化方向，即图中的“一维”，
- 第3个axis(axis = 2)就表示了“三维”方向

![](https://i.imgur.com/qeH9XD3.jpg)

参考：http://jinghuasoft.com/smthview.jsp?board=Python&id=131182

做了一个三维数组示意图，然后每个轴线的操作都看得一清二楚。

![](http://jinghuasoft.com/nForum/att/Python/131182/271.large)

![](http://jinghuasoft.com/nForum/att/Python/131182/23712.large)

In [32]:
np.sum(b)

21

In [33]:
np.sum(b, axis=0)

array([[6, 6],
       [6, 3]])

In [27]:
np.sum(b, axis=1)

array([[ 6,  3],
       [15,  3],
       [24,  3]])

In [28]:
np.sum(b, axis=2)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])