# Summary

- create array
- ndarry 对象属性
- 运算
- 索引和切片
- 数据处理
- 其他

# 一. 数组创建

- 直接创建：np.array()
- 创建均匀间隔数: np.linspace()
- 转换一个array-like 到array: np.asarry()
- ones/one_like
- zeros/zeros_like
- empty/empty_like
- eye/identity: `N*N`矩阵(对角线为1，其余为0)

In [1]:
import numpy as np

In [2]:
np.linspace(2, 3, 5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [3]:
a_like = list('abce')
np.asarray(a_like)

array(['a', 'b', 'c', 'e'], 
      dtype='<U1')

In [4]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# 二.ndarray 对象属性

`.reshape(shape)` 改变数组维度

In [6]:
np.linspace(0, 7, 8)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [8]:
np.linspace(0, 7, 8).reshape(2, 4)   # 2 * 4

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.]])

In [10]:
np.arange(0, 8).reshape(2, 2, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

`.astype(dtype)`改变数组格式

In [15]:
b = np.array([1, 2, 3])
b.dtype

dtype('int64')

In [19]:
b.astype(np.string_)

array([b'1', b'2', b'3'], 
      dtype='|S21')

`.transpose(*axes)` 转置

In [20]:
b = np.arange(8).reshape(2, 4)   # 2 * 4
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
# transpose r * c to c * r
b.T    # or b.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

`.sort` 排序

In [27]:
a = np.array([
    [1, 4],
    [3, 1]
])
np.sort(a)   # axis default is -1, sort along the last axis

array([[1, 4],
       [1, 3]])

In [25]:
np.sort(a, axis=0)  # sort along the first axis

array([[1, 1],
       [3, 4]])

In [26]:
np.sort(a, axis=None)  # sort the flattened array

array([1, 1, 3, 4])